### ISSUE TITLE
Redirect is not working after creating sandbox

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/tugboat#11]
After creating a sandbox, the AJAX handler is not redirecting properly. `ajax_command_redirect()` requires a full URL, like `/demo/foo`, but it's being passed a relative one like `demo/foo`. This results in redirecting to a URL like `/demo/demo/foo` if you're already on the `/demo` page.

```
  if (isset($form_state['redirect'])) {
    $commands[] = ajax_command_redirect($form_state['redirect']);
  }
```

Should be
```
  if (isset($form_state['redirect'])) {
    $commands[] = ajax_command_redirect(url($form_state['redirect']));
  }
```

**Comment by ghost** [comment]
@quicksketch Are you referring to BackdropCMS.org? I'm not experiencing this... I get redirected fine from https://backdropcms.org/demo to https://backdropcms.org/demo/5ebd863e57d91a38ec4b64be. Can you provide STR?

**Comment by ghost** [comment]
Ah nevermind, just experienced this on B.org. Weird how I've never seen it happen there before now...

**Comment by ghost** [comment]
PR here: https://github.com/backdrop-contrib/tugboat/pull/12

@quicksketch Since it's just the code addition you posted above, I'm tempted to just commit it, but I'll leave it a few days in case you want to review it first.

**Comment by ghost** [comment]
Committed, thanks @quicksketch!

**Comment by ghost** [comment]
I also updated the Tugboat module on B.org: https://github.com/backdrop-ops/backdropcms.org/pull/685 so this fix is included there now.
