### ISSUE TITLE
Allow skipping installation

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/tugboat#5]
When you just want to spin up a demo site to test some core functionality, or anything like that, you often don't want to have to go through the installation process each time. It'd be nice if demo sandboxes had an option to skip this and just provide login details like the PR sandboxes do.

I propose adding an option to the 'Create demo' page to skip the install process. I imagine this could be two radio buttons, just not sure what the default should be...

**Comment by klonos** [comment]
Perhaps a single "I also want to test the installer" checkbox, which should be unticked by default?

![Screen Shot 2020-02-21 at 5 51 57 pm](https://user-images.githubusercontent.com/2423362/75011186-124b9f80-54d3-11ea-979d-126c094ee287.png)

...or just 2 buttons that make it clear/simple:

![Screen Shot 2020-02-21 at 5 52 52 pm](https://user-images.githubusercontent.com/2423362/75011213-28596000-54d3-11ea-827e-d16821094b34.png)

**Comment by klonos** [comment]
...or more wordy, but friendly:

![Screen Shot 2020-02-21 at 5 56 25 pm](https://user-images.githubusercontent.com/2423362/75011353-871ed980-54d3-11ea-8ca7-4d8c1c0d357e.png)

**Comment by ghost** [comment]
I think I like the checkbox idea, but maybe put it before/above the button? I'd like to have it unchecked by default (i.e. no installer), but since the current functionality is to run the installer yourself I wonder if it should be checked by default to keep that (if we want it)?

**Comment by quicksketch** [comment]
I don't think we want to run the installer in most cases. While it may provide some minimal benefit in letting people know how it would work if they were to install it themselves, I think most users will be concerned with how the software functions for their primary use-cases, such as creating content or placing blocks.

So I'm +1 for having the installer off by default. My preference would be to omit the option entirely. Or place the checkbox after the button like the first screenshot.

**Comment by ghost** [comment]
Since Tugboat can setup any repository (e.g. Drupal, Wordpress, some-random-cms-no-ones-heard-of, etc.), then the code for automatically installing Backdrop belongs in the `backdrop-tugboat` repo, not this module. So I've made a PR that accomplishes that here: https://github.com/backdrop-ops/backdrop-tugboat/pull/7

It installs Backdrop using the password 'password' and leaves everything else as default. Thoughts?

Once committed, I'll update BackdropCMS.org to add the username and password to the appropriate page.

**Comment by ghost** [comment]
Here's the matching issue for B.org that displays the sandbox username and password to the user: https://github.com/backdrop-ops/backdropcms.org/issues/661

**Comment by ghost** [comment]
The merged PR that removes the Unirest PHP library from this module included some generic changes that'll assist here too.
